### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by VladislavArzamastsev2** [VladislavArzamastsev2/homepage#5]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by VL4DYSL4V** [comment]
My life is devoted to investigations into the unknown,
finding the answers to the mysteries of life and 
training in new technologies.I believe, it's all to do with the
training: you can do a lot if you're properly trained.I am an 
analytical thinker, capable of great concentration and 
theoretical insight. Also I enjoy research and finding 
practical solutions to problems.
