### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by VladislavArzamastsev2** [VladislavArzamastsev2/homepage#6]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by VL4DYSL4V** [comment]
Address: Her Majesty The Queen Buckingham Palace London SW1A 1AA
Twitter: https://twitter.com/royalfamily
Facebook: https://facebook.com/TheBritishMonarchy
Instagram: https://www.instagram.com/theroyalfamily
