### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by VladislavArzamastsev2** [VladislavArzamastsev2/homepage#8]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by VL4DYSL4V** [comment]
Hobbies
1) I am really fond of animals: for much of my life, I was surrounded with dogs - I just adore corgis.
I also own an elephant, two giant turtles, a jaguar and a pair of sloths, 
every sturgeon, porpoise, whale and dolphin in the UK

2) Love different kinds of sports: horse riding, pigeon racing and football – I am an Arsenal supporter

3) Fan of quiet pastimes: I enjoy reading mysteries and working on crossword puzzles 

4) Spending time with family - we usually have so much fun on both of my birthdays 

5) Being the Queen - I am the longest reigning monarch ever in Britain
